--
-- PostgreSQL database dump
--

\restrict QRltt9azaDR3tVajsDfMhhYfNt1bO8a8Jiy1fqdo0zlxVzfLpmasUXtx4jf8Q38

-- Dumped from database version 16.15
-- Dumped by pg_dump version 16.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: alembic_version; Type: TABLE; Schema: public; Owner: anivideos
--

CREATE TABLE public.alembic_version (
    version_num character varying(32) NOT NULL
);


ALTER TABLE public.alembic_version OWNER TO anivideos;

--
-- Name: auth_sessions; Type: TABLE; Schema: public; Owner: anivideos
--

CREATE TABLE public.auth_sessions (
    token_hash character varying(64) NOT NULL,
    user_id bigint NOT NULL,
    expires_at bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.auth_sessions OWNER TO anivideos;

--
-- Name: banner_comments; Type: TABLE; Schema: public; Owner: anivideos
--

CREATE TABLE public.banner_comments (
    id bigint NOT NULL,
    banner_id character varying(140) NOT NULL,
    user_id bigint NOT NULL,
    body character varying(1000) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.banner_comments OWNER TO anivideos;

--
-- Name: banner_comments_id_seq; Type: SEQUENCE; Schema: public; Owner: anivideos
--

ALTER TABLE public.banner_comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.banner_comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: content_items; Type: TABLE; Schema: public; Owner: anivideos
--

CREATE TABLE public.content_items (
    id character varying(120) NOT NULL,
    source character varying(16) NOT NULL,
    external_id character varying(64) NOT NULL,
    category character varying(24) NOT NULL,
    title character varying(200) NOT NULL,
    original_title character varying(200),
    synopsis text DEFAULT ''::text NOT NULL,
    genres jsonb DEFAULT '[]'::jsonb NOT NULL,
    cover_url text NOT NULL,
    backdrop_url text,
    studio character varying(160),
    episodes integer,
    score double precision DEFAULT '0'::double precision NOT NULL,
    release_year integer,
    maturity character varying(24) DEFAULT 'NR'::character varying NOT NULL,
    format character varying(32) NOT NULL,
    status character varying(32) NOT NULL,
    origin character varying(80) DEFAULT ''::character varying NOT NULL,
    trailer_youtube_id character varying(32),
    official_url text,
    platform_links jsonb DEFAULT '[]'::jsonb NOT NULL,
    source_url text,
    provider_updated_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_content_category CHECK (((category)::text = ANY ((ARRAY['anime'::character varying, 'k-drama'::character varying, 'j-drama'::character varying, 'donghua'::character varying, 'movie'::character varying, 'ova'::character varying])::text[]))),
    CONSTRAINT ck_content_score CHECK (((score >= (0)::double precision) AND (score <= (10)::double precision))),
    CONSTRAINT ck_content_source CHECK (((source)::text = ANY ((ARRAY['anilist'::character varying, 'tmdb'::character varying])::text[])))
);


ALTER TABLE public.content_items OWNER TO anivideos;

--
-- Name: favorites; Type: TABLE; Schema: public; Owner: anivideos
--

CREATE TABLE public.favorites (
    user_id bigint NOT NULL,
    content_id character varying(120) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.favorites OWNER TO anivideos;

--
-- Name: featured_banners; Type: TABLE; Schema: public; Owner: anivideos
--

CREATE TABLE public.featured_banners (
    id character varying(140) NOT NULL,
    content_id character varying(120) NOT NULL,
    eyebrow character varying(120) NOT NULL,
    display_order integer DEFAULT 0 NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.featured_banners OWNER TO anivideos;

--
-- Name: users; Type: TABLE; Schema: public; Owner: anivideos
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    username character varying(40) NOT NULL,
    email character varying(254) NOT NULL,
    password_hash character varying(255) NOT NULL,
    avatar_url text,
    display_name character varying(60),
    bio character varying(280),
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.users OWNER TO anivideos;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: anivideos
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: alembic_version; Type: TABLE DATA; Schema: public; Owner: anivideos
--

COPY public.alembic_version (version_num) FROM stdin;
001_v16_postgresql
\.


--
-- Data for Name: auth_sessions; Type: TABLE DATA; Schema: public; Owner: anivideos
--

COPY public.auth_sessions (token_hash, user_id, expires_at, created_at) FROM stdin;
\.


--
-- Data for Name: banner_comments; Type: TABLE DATA; Schema: public; Owner: anivideos
--

COPY public.banner_comments (id, banner_id, user_id, body, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: content_items; Type: TABLE DATA; Schema: public; Owner: anivideos
--

COPY public.content_items (id, source, external_id, category, title, original_title, synopsis, genres, cover_url, backdrop_url, studio, episodes, score, release_year, maturity, format, status, origin, trailer_youtube_id, official_url, platform_links, source_url, provider_updated_at, created_at, updated_at) FROM stdin;
anilist-16498	anilist	16498	anime	Attack on Titan	進撃の巨人	Several hundred years ago, humans were nearly exterminated by titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a city protected by extremely high walls, even taller than the biggest of titans. Flash forward to the present and the city has not seen a titan in over 100 years. Teenage boy Eren and his foster sister Mikasa witness something horrific as the city walls are destroyed by a colossal titan that appears out of thin air. As the smaller titans flood the city, the two kids watch in horror as their mother is eaten alive. Eren vows that he will murder every single titan and take revenge for all of mankind. (Source: MangaHelpers)	["Action", "Drama", "Fantasy", "Mystery"]	https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx16498-buvcRTBx4NSm.jpg	https://s4.anilist.co/file/anilistcdn/media/anime/banner/16498-8jpFCOcDmneX.jpg	WIT STUDIO	25	8.5	2013	NR	tv	finished	JP	LHtdKWJdif4\t	https://anilist.co/anime/16498	[{"url": "https://www.adultswim.com/videos/attack-on-titan", "name": "Adult Swim"}, {"url": "https://www.iq.com/album/xq12ps94l5", "name": "iQ"}, {"url": "https://youtube.com/@attackontitan_officialchannel", "name": "YouTube"}]	https://anilist.co/anime/16498	2026-10-07 00:29:48.598562+00	2026-10-07 00:29:48.621627+00	2026-10-07 00:29:48.621627+00
anilist-101922	anilist	101922	anime	Demon Slayer: Kimetsu no Yaiba	鬼滅の刃	It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon. To make matters worse, his younger sister Nezuko, the sole survivor, has been transformed into a demon herself. Though devastated by this grim reality, Tanjiro resolves to become a “demon slayer” so that he can turn his sister back into a human, and kill the demon that massacred his family. (Source: Crunchyroll)	["Action", "Adventure", "Drama", "Fantasy", "Supernatural"]	https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101922-WBsBl0ClmgYL.jpg	https://s4.anilist.co/file/anilistcdn/media/anime/banner/101922-33MtJGsUSxga.jpg	ufotable	26	8.2	2019	NR	tv	finished	JP	6vMuWuWlW4I	https://anilist.co/anime/101922	[{"url": "https://www.crunchyroll.com/demon-slayer-kimetsu-no-yaiba", "name": "Crunchyroll"}, {"url": "https://www.hulu.com/demon-slayer-kimetsu-no-yaiba", "name": "Hulu"}, {"url": "https://www.netflix.com/title/81091393", "name": "Netflix"}]	https://anilist.co/anime/101922	2026-10-07 00:29:48.598617+00	2026-10-07 00:29:48.621627+00	2026-10-07 00:29:48.621627+00
anilist-113415	anilist	113415	anime	JUJUTSU KAISEN	呪術廻戦	A boy fights... for "the right death." Hardship, regret, shame: the negative feelings that humans feel become Curses that lurk in our everyday lives. The Curses run rampant throughout the world, capable of leading people to terrible misfortune and even death. What's more, the Curses can only be exorcised by another Curse. Itadori Yuji is a boy with tremendous physical strength, though he lives a completely ordinary high school life. One day, to save a friend who has been attacked by Curses, he eats the finger of the Double-Faced Specter, taking the Curse into his own soul. From then on, he shares one body with the Double-Faced Specter. Guided by the most powerful of sorcerers, Gojou Satoru, Itadori is admitted to the Tokyo Metropolitan Technical High School of Sorcery, an organization that fights the Curses... and thus begins the heroic tale of a boy who became a Curse to exorcise a Curse, a life from which he could never turn back. (Source: Crunchyroll) Note: The first episode received an early web premiere on September 19th, 2020. The regular TV broadcast started on October 3rd, 2020.	["Action", "Drama", "Supernatural"]	https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx113415-LHBAeoZDIsnF.jpg	https://s4.anilist.co/file/anilistcdn/media/anime/banner/113415-jQBSkxWAAk83.jpg	MAPPA	24	8.4	2020	NR	tv	finished	JP	RIyb52EMx8c	https://anilist.co/anime/113415	[{"url": "https://www.crunchyroll.com/jujutsu-kaisen", "name": "Crunchyroll"}, {"url": "https://www.netflix.com/title/81278456", "name": "Netflix"}, {"url": "https://www.iq.com/album/igc33vhvex", "name": "iQ"}, {"url": "https://www.bilibili.tv/media/37738", "name": "Bilibili TV"}, {"url": "https://youtube.com/playlist?list=PLxSscENEp7JisDU6GAJuyNpVwDvCm-f3J", "name": "YouTube"}, {"url": "https://www.hulu.com/series/jujutsu-kaisen-382ec8bf-3650-4cde-94db-ecd18665f9e0", "name": "Hulu"}]	https://anilist.co/anime/113415	2026-10-07 00:29:48.598685+00	2026-10-07 00:29:48.621627+00	2026-10-07 00:29:48.621627+00
anilist-1535	anilist	1535	anime	Death Note	DEATH NOTE	Light Yagami is a genius high school student who is about to learn about life through a book of death. When a bored shinigami, a God of Death, named Ryuk drops a black notepad called a Death Note , Light receives power over life and death with the stroke of a pen. Determined to use this dark gift for the best, Light sets out to rid the world of evil… namely, the people he believes to be evil. Should anyone hold such power? The consequences of Light’s actions will set the world ablaze. (Source: VIZ Media)	["Mystery", "Psychological", "Supernatural", "Thriller"]	https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx1535-kUgkcrfOrkUM.jpg	https://s4.anilist.co/file/anilistcdn/media/anime/banner/1535.jpg	MADHOUSE	37	8.4	2006	NR	tv	finished	JP	NlJZ-YgAt-c	https://anilist.co/anime/1535	[{"url": "https://www.netflix.com/title/70204970", "name": "Netflix"}, {"url": "https://tubitv.com/series/1630/death_note", "name": "Tubi TV"}, {"url": "https://www.amazon.com/Death-Note/dp/B0B6RMGK8Z", "name": "Amazon Prime Video"}, {"url": "https://youtube.com/playlist?list=PLDDFkfLheQ9hzlWtnCSla1DicLZkllriY", "name": "YouTube"}, {"url": "https://www.hoopladigital.com/television/death-note-subbed-season-1-mamoru-miyano/14733965", "name": "Hoopla"}, {"url": "https://www.hoopladigital.com/television/death-note-dubbed-season-1-mamoru-miyano/14733986", "name": "Hoopla"}, {"url": "https://www.crunchyroll.com/series/G6QWD3EE6", "name": "Crunchyroll"}]	https://anilist.co/anime/1535	2026-10-07 00:29:48.598727+00	2026-10-07 00:29:48.621627+00	2026-10-07 00:29:48.621627+00
anilist-21459	anilist	21459	anime	My Hero Academia	僕のヒーローアカデミア	What would the world be like if 80 percent of the population manifested extraordinary superpowers called “Quirks” at age four? Heroes and villains would be battling it out everywhere! Becoming a hero would mean learning to use your power, but where would you go to study? U.A. High's Hero Program of course! But what would you do if you were one of the 20 percent who were born Quirkless? Middle school student Izuku Midoriya wants to be a hero more than anything, but he hasn't got an ounce of power in him. With no chance of ever getting into the prestigious U.A. High School for budding heroes, his life is looking more and more like a dead end. Then an encounter with All Might, the greatest hero of them all gives him a chance to change his destiny… (Source: VIZ Media)	["Action", "Adventure", "Comedy"]	https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21459-nYh85uj2Fuwr.jpg	https://s4.anilist.co/file/anilistcdn/media/anime/banner/21459-yeVkolGKdGUV.jpg	bones	13	7.6	2016	NR	tv	finished	JP	AhqVltWDqFA	https://anilist.co/anime/21459	[{"url": "https://www.netflix.com/title/80135674", "name": "Netflix"}, {"url": "https://www.iq.com/album/1djwf83pp09", "name": "iQ"}]	https://anilist.co/anime/21459	2026-10-07 00:29:48.598778+00	2026-10-07 00:29:48.621627+00	2026-10-07 00:29:48.621627+00
anilist-11061	anilist	11061	anime	Hunter x Hunter (2011)	HUNTER×HUNTER (2011)	A Hunter is one who travels the world doing all sorts of dangerous tasks. From capturing criminals to searching deep within uncharted lands for any lost treasures. Gon is a young boy whose father disappeared long ago, being a Hunter. He believes if he could also follow his father's path, he could one day reunite with him. After becoming 12, Gon leaves his home and takes on the task of entering the Hunter exam, notorious for its low success rate and high probability of death to become an official Hunter. He befriends the revenge-driven Kurapika, the doctor-to-be Leorio and the rebellious ex-assassin Killua in the exam, with their friendship prevailing throughout the many trials and threats they come upon taking on the dangerous career of a Hunter.	["Action", "Adventure", "Fantasy"]	https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx11061-y5gsT1hoHuHw.png	https://s4.anilist.co/file/anilistcdn/media/anime/banner/11061-8WkkTZ6duKpq.jpg	MADHOUSE	148	8.9	2011	NR	tv	finished	JP	d6kBeJjTGnY	https://anilist.co/anime/11061	[{"url": "https://www.hulu.com/hunter-x-hunter", "name": "Hulu"}, {"url": "https://www.netflix.com/title/70300472", "name": "Netflix"}, {"url": "https://tubitv.com/series/1627/hunter_x_hunter", "name": "Tubi TV"}, {"url": "https://www.bilibili.tv/en/play/37603", "name": "Bilibili"}, {"url": "https://youtube.com/playlist?list=PLwLSw1_eDZl2SdSro00Nvg38MQUf-5ZL8", "name": "YouTube"}, {"url": "https://www.hoopladigital.com/series/hunter-x-hunter-dubbed/11834349593", "name": "Hoopla"}, {"url": "https://www.hoopladigital.com/series/hunter-x-hunter-subbed/11834349354", "name": "Hoopla"}, {"url": "https://www.amazon.com/Hunter-Japanese-English-Subs/dp/B0B5X87G1P", "name": "Amazon Prime Video"}]	https://anilist.co/anime/11061	2026-10-07 00:29:48.598829+00	2026-10-07 00:29:48.621627+00	2026-10-07 00:29:48.621627+00
anilist-21087	anilist	21087	anime	One-Punch Man	ワンパンマン	Saitama has a rather peculiar hobby, being a superhero, but despite his heroic deeds and superhuman abilities, a shadow looms over his life. He's become much too powerful, to the point that every opponent ends up defeated with a single punch. The lack of challenge has driven him into a state of apathy, as he watches his life pass by having lost all enthusiasm, at least until he's unwillingly thrust in the role of being a mentor to the young and revenge-driven Genos.	["Action", "Comedy", "Sci-Fi", "Supernatural"]	https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21087-B5DHjqZ3kW4b.jpg	https://s4.anilist.co/file/anilistcdn/media/anime/banner/21087-sHb9zUZFsHe1.jpg	MADHOUSE	12	8.2	2015	NR	tv	finished	JP	RzmFKUDOUgw	https://anilist.co/anime/21087	[{"url": "https://www.netflix.com/title/80117291", "name": "Netflix"}, {"url": "https://www.youtube.com/playlist?list=PLwLSw1_eDZl2XdtLhB9NG2Ch050jWFm9G", "name": "YouTube"}, {"url": "https://wetv.vip/id/play/r386s7hzwidwkpv/r0035owmbkx", "name": "WeTV"}, {"url": "https://www.iq.com/album/2ekpp4jtbwt", "name": "iQ"}, {"url": "https://www.bilibili.tv/media/36279", "name": "Bilibili TV"}, {"url": "https://www.youtube.com/playlist?list=PLpm1VVK4UL16FvVk0QOffUwXX_vaHVjZP", "name": "YouTube"}, {"url": "https://www.youtube.com/playlist?list=PLwLSw1_eDZl0YZIflIt1EK0dcjLuMuxLd", "name": "YouTube"}]	https://anilist.co/anime/21087	2026-10-07 00:29:48.598859+00	2026-10-07 00:29:48.621627+00	2026-10-07 00:29:48.621627+00
anilist-21	anilist	21	anime	ONE PIECE	ONE PIECE	Gold Roger was known as the Pirate King, the strongest and most infamous being to have sailed the Grand Line. The capture and death of Roger by the World Government brought a change throughout the world. His last words before his death revealed the location of the greatest treasure in the world, One Piece. It was this revelation that brought about the Grand Age of Pirates, men who dreamed of finding One Piece (which promises an unlimited amount of riches and fame), and quite possibly the most coveted of titles for the person who found it, the title of the Pirate King. Enter Monkey D. Luffy, a 17-year-old boy that defies your standard definition of a pirate. Rather than the popular persona of a wicked, hardened, toothless pirate who ransacks villages for fun, Luffy’s reason for being a pirate is one of pure wonder; the thought of an exciting adventure and meeting new and intriguing people, along with finding One Piece, are his reasons of becoming a pirate. Following in the footsteps of his childhood hero, Luffy and his crew travel across the Grand Line, experiencing crazy adventures, unveiling dark mysteries and battling strong enemies, all in order to reach One Piece. *This includes the following special episodes: - Chopperman to the Rescue! Protect the TV Station by the Shore! (Episode 336) - The Strongest Tag-Team! Luffy and Toriko's Hard Struggle! (Episode 492) - Team Formation! Save Chopper (Episode 542) - History's Strongest Collaboration vs. Glutton of the Sea (Episode 590) - 20th Anniversary! Special Romance Dawn (Episode 907)	["Action", "Adventure", "Comedy", "Drama", "Fantasy"]	https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21-ELSYx3yMPcKM.jpg	https://s4.anilist.co/file/anilistcdn/media/anime/banner/21-wf37VakJmZqs.jpg	Toei Animation	\N	8.7	1999	NR	tv	airing	JP	\N	https://anilist.co/anime/21	[{"url": "https://www.netflix.com/title/80107103", "name": "Netflix"}, {"url": "https://www.bilibili.tv/media/37976", "name": "Bilibili TV"}, {"url": "https://www.iq.com/album/1bk9icvr331", "name": "iQ"}, {"url": "https://wetv.vip/en/play/tnfk3rniubz3m8o", "name": "WeTV"}, {"url": "https://www.youtube.com/@onepieceofficial", "name": "YouTube"}, {"url": "https://www.hoopladigital.com/series/one-piece/14153295320", "name": "Hoopla"}, {"url": "https://www.youtube.com/@OnePieceOfficialENG", "name": "YouTube"}]	https://anilist.co/anime/21	2026-10-07 00:29:48.598951+00	2026-10-07 00:29:48.621627+00	2026-10-07 00:29:48.621627+00
anilist-20605	anilist	20605	anime	Tokyo Ghoul	東京喰種 トーキョーグール	The suspense horror/dark fantasy story is set in Tokyo, which is haunted by mysterious "ghouls" who are devouring humans. People are gripped by the fear of these ghouls whose identities are masked in mystery. An ordinary college student named Kaneki encounters Rize, a girl who is an avid reader like him, at the café he frequents. Little does he realize that his fate will change overnight. (Source: Anime News Network)	["Action", "Drama", "Horror", "Mystery", "Psychological", "Supernatural"]	https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/b20605-k665mVkSug8D.jpg	https://s4.anilist.co/file/anilistcdn/media/anime/banner/20605-RCJ7M71zLmrh.jpg	Studio Pierrot	12	7.6	2014	NR	tv	finished	JP	XfQUjYsVBrE	https://anilist.co/anime/20605	[{"url": "https://www.amazon.com/gp/video/detail/B015O6OK4G/", "name": "Amazon Prime Video"}, {"url": "https://www.crunchyroll.com/en-gb/tokyo-ghoul", "name": "Crunchyroll"}, {"url": "https://www.netflix.com/title/80023687", "name": "Netflix"}]	https://anilist.co/anime/20605	2026-10-07 00:29:48.598984+00	2026-10-07 00:29:48.621627+00	2026-10-07 00:29:48.621627+00
anilist-20958	anilist	20958	anime	Attack on Titan Season 2	進撃の巨人 Season２	Eren Jaeger swore to wipe out every last Titan, but in a battle for his life he wound up becoming the thing he hates most. With his new powers, he fights for humanity's freedom facing the monsters that threaten his home. After a bittersweet victory against the Female Titan, Eren finds no time to rest—a horde of Titans is approaching Wall Rose and the battle for humanity continues! (Source: Funimation)	["Action", "Drama", "Fantasy", "Mystery"]	https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20958-HuFJyr54Mmir.jpg	https://s4.anilist.co/file/anilistcdn/media/anime/banner/20958-Y7eQdz9VENBD.jpg	WIT STUDIO	12	8.5	2017	NR	tv	finished	JP	zLaVP8IhIuc	https://anilist.co/anime/20958	[{"url": "https://www.hulu.com/attack-on-titan", "name": "Hulu"}, {"url": "https://www.adultswim.com/videos/attack-on-titan", "name": "Adult Swim"}, {"url": "https://www.iq.com/album/1f7yemxzyr5", "name": "iQ"}, {"url": "https://www.netflix.com/title/70299043", "name": "Netflix"}, {"url": "https://www.crunchyroll.com/attack-on-titan-dubs", "name": "Crunchyroll"}]	https://anilist.co/anime/20958	2026-10-07 00:29:48.599019+00	2026-10-07 00:29:48.621627+00	2026-10-07 00:29:48.621627+00
anilist-5114	anilist	5114	anime	Fullmetal Alchemist: Brotherhood	鋼の錬金術師 FULLMETAL ALCHEMIST	"In order for something to be obtained, something of equal value must be lost." Alchemy is bound by this Law of Equivalent Exchange—something the young brothers Edward and Alphonse Elric only realize after attempting human transmutation: the one forbidden act of alchemy. They pay a terrible price for their transgression—Edward loses his left leg, Alphonse his physical body. It is only by the desperate sacrifice of Edward's right arm that he is able to affix Alphonse's soul to a suit of armor. Devastated and alone, it is the hope that they would both eventually return to their original bodies that gives Edward the inspiration to obtain metal limbs called "automail" and become a state alchemist, the Fullmetal Alchemist. Three years of searching later, the brothers seek the Philosopher's Stone, a mythical relic that allows an alchemist to overcome the Law of Equivalent Exchange. Even with military allies Colonel Roy Mustang, Lieutenant Riza Hawkeye, and Lieutenant Colonel Maes Hughes on their side, the brothers find themselves caught up in a nationwide conspiracy that leads them not only to the true nature of the elusive Philosopher's Stone, but their country's murky history as well. In between finding a serial killer and racing against time, Edward and Alphonse must ask themselves if what they are doing will make them human again... or take away their humanity. (Source: MAL Rewrite)	["Action", "Adventure", "Drama", "Fantasy"]	https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx5114-nSWCgQlmOMtj.jpg	https://s4.anilist.co/file/anilistcdn/media/anime/banner/5114-q0V5URebphSG.jpg	bones	64	9	2009	NR	tv	finished	JP	1ac3_YdSSy0	https://anilist.co/anime/5114	[{"url": "https://www.amazon.com/One-All/dp/B002T8C202/ref=sr_1_52/146-1307517-0174061?s=instant-video&rps=1&ie=UTF8&qid=1528858933&sr=1-52&refinements=p_n_theme_browse-bin%3A2650364011%2Cp_85%3A2470955011%2Cp_n_entity_type%3A14069184011%7C14069185011", "name": "Amazon Prime Video"}, {"url": "https://www.netflix.com/title/70204981", "name": "Netflix"}, {"url": "https://www.iq.com/album/s8lu95if3p", "name": "iQ"}]	https://anilist.co/anime/5114	2026-10-07 00:29:48.599106+00	2026-10-07 00:29:48.621627+00	2026-10-07 00:29:48.621627+00
anilist-20	anilist	20	anime	Naruto	NARUTO -ナルト-	Naruto Uzumaki, a hyperactive and knuckle-headed ninja, lives in Konohagakure, the Hidden Leaf village. Moments prior to his birth, a huge demon known as the Kyuubi, the Nine-tailed Fox, attacked Konohagakure and wreaked havoc. In order to put an end to the Kyuubi's rampage, the leader of the village, the 4th Hokage, sacrificed his life and sealed the monstrous beast inside the newborn Naruto. Shunned because of the presence of the Kyuubi inside him, Naruto struggles to find his place in the village. He strives to become the Hokage of Konohagakure, and he meets many friends and foes along the way. (Source: MAL Rewrite)	["Action", "Adventure", "Comedy", "Drama", "Fantasy", "Supernatural"]	https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20-dE6UHbFFg1A5.jpg	https://s4.anilist.co/file/anilistcdn/media/anime/banner/20-HHxhPj5JD13a.jpg	Studio Pierrot	220	8	2002	NR	tv	finished	JP	-G9BqkgZXRA	https://anilist.co/anime/20	[{"url": "https://www.netflix.com/title/70205012", "name": "Netflix"}, {"url": "https://tubitv.com/series/1622/naruto", "name": "Tubi TV"}, {"url": "https://www.bilibili.tv/en/play/1005144", "name": "Bilibili"}, {"url": "https://www.iq.com/album/naruto-1evx2uy83ah", "name": "iQ"}, {"url": "https://youtube.com/playlist?list=PLDDFkfLheQ9hNru7WoTa26dpn6o9-AEJK", "name": "YouTube"}, {"url": "https://www.hoopladigital.com/series/naruto-dubbed/11802118009", "name": "Hoopla"}, {"url": "https://www.hoopladigital.com/television/naruto-subbed-season-1/14608874", "name": "Hoopla"}]	https://anilist.co/anime/20	2026-10-07 00:29:48.599146+00	2026-10-07 00:29:48.621627+00	2026-10-07 00:29:48.621627+00
anilist-11757	anilist	11757	anime	Sword Art Online	ソードアート・オンライン	In the near future, a Virtual Reality Massive Multiplayer Online Role-Playing Game (VRMMORPG) called Sword Art Online has been released where players control their avatars with their bodies using a piece of technology called Nerve Gear. One day, players discover they cannot log out, as the game creator is holding them captive unless they reach the 100th floor of the game's tower and defeat the final boss. However, if they die in the game, they die in real life. Their struggle for survival starts now... (Source: Crunchyroll)	["Action", "Adventure", "Fantasy", "Romance"]	https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx11757-SxYDUzdr9rh2.jpg	https://s4.anilist.co/file/anilistcdn/media/anime/banner/11757-TlEEV9weG4Ag.jpg	A-1 Pictures	25	7	2012	NR	tv	finished	JP	C8Jl_-b7ju0	https://anilist.co/anime/11757	[{"url": "https://www.netflix.com/title/70302573", "name": "Netflix"}, {"url": "https://www.iq.com/album/1sm7i4izi51", "name": "iQ"}, {"url": "https://www.bilibili.tv/media/35932", "name": "Bilibili TV"}]	https://anilist.co/anime/11757	2026-10-07 00:29:48.599178+00	2026-10-07 00:29:48.621627+00	2026-10-07 00:29:48.621627+00
anilist-20954	anilist	20954	anime	A Silent Voice	聲の形	After transferring into a new school, a deaf girl, Shouko Nishimiya, is bullied by the popular Shouya Ishida. As Shouya continues to bully Shouko, the class turns its back on him. Shouko transfers and Shouya grows up as an outcast. Alone and depressed, the regretful Shouya finds Shouko to make amends. (Source: Eleven Arts)	["Drama", "Romance", "Slice of Life"]	https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20954-sYRfE5jQRtSB.jpg	https://s4.anilist.co/file/anilistcdn/media/anime/banner/20954-f30bHMXa5Qoe.jpg	Kyoto Animation	1	8.8	2016	NR	movie	finished	JP	Sy4bPCuzfiQ	https://anilist.co/anime/20954	[{"url": "https://www.netflix.com/title/80223226", "name": "Netflix"}]	https://anilist.co/anime/20954	2026-10-07 00:29:48.5992+00	2026-10-07 00:29:48.621627+00	2026-10-07 00:29:48.621627+00
anilist-21519	anilist	21519	anime	Your Name.	君の名は。	Mitsuha Miyamizu, a high school girl, yearns to live the life of a boy in the bustling city of Tokyo—a dream that stands in stark contrast to her present life in the countryside. Meanwhile in the city, Taki Tachibana lives a busy life as a high school student while juggling his part-time job and hopes for a future in architecture. One day, Mitsuha awakens in a room that is not her own and suddenly finds herself living the dream life in Tokyo—but in Taki's body! Elsewhere, Taki finds himself living Mitsuha's life in the humble countryside. In pursuit of an answer to this strange phenomenon, they begin to search for one another. Kimi no Na wa. revolves around Mitsuha and Taki's actions, which begin to have a dramatic impact on each other's lives, weaving them into a fabric held together by fate and circumstance. (Source: MAL Rewrite)	["Drama", "Romance", "Supernatural"]	https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21519-SUo3ZQuCbYhJ.png	https://s4.anilist.co/file/anilistcdn/media/anime/banner/21519-1ayMXgNlmByb.jpg	CoMix Wave	1	8.5	2016	NR	movie	finished	JP	k4xGqY5IDBE	https://anilist.co/anime/21519	[{"url": "https://www.netflix.com/title/80161371", "name": "Netflix"}, {"url": "https://www.crunchyroll.com/your-name", "name": "Crunchyroll"}, {"url": "https://www.primevideo.com/detail/0LQ7ANJUT17XBYKOFOUCQ1PORE", "name": "Amazon Prime Video"}, {"url": "https://play.max.com/movie/e95b27d7-7fba-4b3b-bed9-a134dd1bc6ba", "name": "Max"}]	https://anilist.co/anime/21519	2026-10-07 00:29:48.599252+00	2026-10-07 00:29:48.621627+00	2026-10-07 00:29:48.621627+00
anilist-99147	anilist	99147	anime	Attack on Titan Season 3	進撃の巨人 Season３	Eren and his companions in the 104th are assigned to the newly-formed Levi Squad, whose assignment is to keep Eren and Historia safe given Eren's newly-discovered power and Historia's knowledge and pedigree. Levi and Erwin have good reason to be concerned, because the priest of the Church that Hanji had hidden away was found tortured to death, making it clear that the Military Police are involved with the cover-up. Things get more harrowing when the MPs make a move on Erwin and the Levi Squad narrowly avoids capture. Eren is also having problems with his Titan transformation, and a deadly killer has been hired to secure Eren and Historia, one Levi knows all too well from his youth. (Source: Anime News Network)	["Action", "Drama", "Fantasy", "Mystery"]	https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx99147-AiPDD8cwlCfi.jpg	https://s4.anilist.co/file/anilistcdn/media/anime/banner/99147-HACsFVrynFf5.jpg	WIT STUDIO	12	8.6	2018	NR	tv	finished	JP	EHzBhrncmac	https://anilist.co/anime/99147	[{"url": "https://www.hulu.com/attack-on-titan", "name": "Hulu"}, {"url": "https://www.adultswim.com/videos/attack-on-titan", "name": "Adult Swim"}, {"url": "https://www.iq.com/album/2c19tvbcbux", "name": "iQ"}, {"url": "https://www.netflix.com/title/70299043", "name": "Netflix"}, {"url": "https://www.crunchyroll.com/attack-on-titan-dubs", "name": "Crunchyroll"}]	https://anilist.co/anime/99147	2026-10-07 00:29:48.599291+00	2026-10-07 00:29:48.621627+00	2026-10-07 00:29:48.621627+00
anilist-21856	anilist	21856	anime	My Hero Academia Season 2	僕のヒーローアカデミア２	Taking off right after the last episode of the first season. The school is temporarily closed due to security. When U.A. restarts, it is announced that the highly anticipated School Sports Festival will soon be taking place. All classes: Hero, Support, General and Business will be participating. Tournaments all round will decide who is the top Hero in training. (Source: Anime News Network)	["Action", "Adventure", "Comedy"]	https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21856-gutauxhWAwn6.png	https://s4.anilist.co/file/anilistcdn/media/anime/banner/21856-wtSHgeHFmzdG.jpg	bones	25	7.9	2017	NR	tv	finished	JP	tEPneR3KFK8	https://anilist.co/anime/21856	[{"url": "https://www.hulu.com/my-hero-academia", "name": "Hulu"}, {"url": "https://www.netflix.com/title/80135674", "name": "Netflix"}, {"url": "https://www.iq.com/album/n86sxek1nt", "name": "iQ"}, {"url": "https://www.crunchyroll.com/my-hero-academia-dubs", "name": "Crunchyroll"}]	https://anilist.co/anime/21856	2026-10-07 00:29:48.599325+00	2026-10-07 00:29:48.621627+00	2026-10-07 00:29:48.621627+00
anilist-110277	anilist	110277	anime	Attack on Titan Final Season	進撃の巨人 The Final Season	It’s been four years since the Scout Regiment reached the shoreline, and the world looks different now. Things are heating up as the fate of the Scout Regiment—and the people of Paradis—are determined at last. However, Eren is missing. Will he reappear before age-old tensions between Marleyans and Eldians result in the war of all wars? (Source: Crunchyroll)	["Action", "Drama", "Fantasy", "Mystery"]	https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx110277-sKUNXAsWMNFw.jpg	https://s4.anilist.co/file/anilistcdn/media/anime/banner/110277-iuGn6F5bK1U1.jpg	MAPPA	16	8.7	2021	NR	tv	finished	JP	MUCN-JwUvbY	https://anilist.co/anime/110277	[{"url": "https://www.crunchyroll.com/attack-on-titan", "name": "Crunchyroll"}, {"url": "https://www.hulu.com/series/attack-on-titan-9c91ffa3-dc20-48bf-8bc5-692e37c76d88", "name": "Hulu"}, {"url": "https://www.adultswim.com/videos/attack-on-titan", "name": "Adult Swim"}, {"url": "https://www.iq.com/album/26rwd8fpbix", "name": "iQ"}, {"url": "https://www.netflix.com/title/70299043", "name": "Netflix"}, {"url": "https://www.crunchyroll.com/attack-on-titan-dubs", "name": "Crunchyroll"}]	https://anilist.co/anime/110277	2026-10-07 00:29:48.599354+00	2026-10-07 00:29:48.621627+00	2026-10-07 00:29:48.621627+00
anilist-127230	anilist	127230	anime	Chainsaw Man	チェンソーマン	Denji is a teenage boy living with a Chainsaw Devil named Pochita. Due to the debt his father left behind, he has been living a rock-bottom life while repaying his debt by harvesting devil corpses with Pochita. One day, Denji is betrayed and killed. As his consciousness fades, he makes a contract with Pochita and gets revived as "Chainsaw Man" — a man with a devil's heart. (Source: Crunchyroll)	["Action", "Drama", "Horror", "Supernatural"]	https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx127230-DdP4vAdssLoz.png	https://s4.anilist.co/file/anilistcdn/media/anime/banner/127230-o8IRwCGVr9KW.jpg	MAPPA	12	8.3	2022	NR	tv	finished	JP	v4yLeNt-kCU	https://anilist.co/anime/127230	[{"url": "https://crunchyroll.com/series/GVDHX8QNW", "name": "Crunchyroll"}, {"url": "https://www.youtube.com/playlist?list=PLxSscENEp7JhfvHiWN-djJjCOjW8rxA6p", "name": "YouTube"}, {"url": "https://www.hulu.com/series/chainsaw-man-7b71b5a4-560b-4d8b-98c4-c5dee6004c21", "name": "Hulu"}, {"url": "https://www.bilibili.tv/en/media/2069687", "name": "Bilibili TV"}, {"url": "https://www.disneyplus.com/series/chainsaw-man/2gMK1kC3JIEh", "name": "Disney Plus"}, {"url": "https://www.netflix.com/title/81215627", "name": "Netflix"}]	https://anilist.co/anime/127230	2026-10-07 00:29:48.599387+00	2026-10-07 00:29:48.621627+00	2026-10-07 00:29:48.621627+00
anilist-101759	anilist	101759	anime	The Promised Neverland	約束のネバーランド	Emma, Norman and Ray are the brightest kids at the Grace Field House orphanage. And under the care of the woman they refer to as “Mom,” all the kids have enjoyed a comfortable life. Good food, clean clothes and the perfect environment to learn—what more could an orphan ask for? One day, though, Emma and Norman uncover the dark truth of the outside world they are forbidden from seeing. (Source: VIZ Media)	["Drama", "Fantasy", "Horror", "Mystery", "Psychological", "Thriller"]	https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101759-8UR7r9MNVpz2.jpg	https://s4.anilist.co/file/anilistcdn/media/anime/banner/101759-MhlCoeqnODso.jpg	CloverWorks	12	8.3	2019	NR	tv	finished	JP	ApLudqucq-s	https://anilist.co/anime/101759	[{"url": "https://www.crunchyroll.com/the-promised-neverland", "name": "Crunchyroll"}, {"url": "https://www.hulu.com/the-promised-neverland", "name": "Hulu"}, {"url": "https://www.netflix.com/title/81145640", "name": "Netflix"}, {"url": "https://www.iq.com/album/fqzoj5ytxt", "name": "iQ"}]	https://anilist.co/anime/101759	2026-10-07 00:29:48.599416+00	2026-10-07 00:29:48.621627+00	2026-10-07 00:29:48.621627+00
anilist-20755	anilist	20755	anime	Assassination Classroom	暗殺教室	The students of class 3-E have a mission: kill their teacher before graduation. He has already destroyed the moon, and has promised to destroy the Earth if he can not be killed within a year. But how can this class of misfits kill a tentacled monster, capable of reaching Mach 20 speed, who may be the best teacher any of them have ever had?	["Action", "Comedy", "Drama", "Supernatural"]	https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20755-dWrhs569YGUO.jpg	https://s4.anilist.co/file/anilistcdn/media/anime/banner/20755-D4ipww9U8YkC.jpg	Lerche	22	7.9	2015	NR	tv	finished	JP	vAuTJFzjNLs	https://anilist.co/anime/20755	[{"url": "https://www.youtube.com/playlist?list=PLwLSw1_eDZl1QGs4v-QtvNHpC_N8ZjkEs", "name": "YouTube"}, {"url": "https://www.crunchyroll.com/assassination-classroom", "name": "Crunchyroll"}]	https://anilist.co/anime/20755	2026-10-07 00:29:48.599439+00	2026-10-07 00:29:48.621627+00	2026-10-07 00:29:48.621627+00
anilist-21507	anilist	21507	anime	Mob Psycho 100	モブサイコ100	The story revolves around "Mob," a boy who will explode if his emotional capacity reaches 100%. This boy with psychic powers earned his nickname "Mob" because he does not stand out among other people. He keeps his psychic powers bottled up so he can live normally, but if his emotional level reaches 100, something will overwhelm his entire body. (Source: Anime News Network)	["Action", "Comedy", "Drama", "Psychological", "Slice of Life", "Supernatural"]	https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21507-6YUSbh2m0N1p.jpg	https://s4.anilist.co/file/anilistcdn/media/anime/banner/21507-Qx8bGsLXUgLo.jpg	bones	12	8.4	2016	NR	tv	finished	JP	mV39saBlBLI	https://anilist.co/anime/21507	[{"url": "https://www.netflix.com/title/80179798", "name": "Netflix"}, {"url": "https://www.youtube.com/playlist?list=PLpm1VVK4UL15H3VL53aWCCaCk_pkpJ5u-", "name": "YouTube"}, {"url": "https://www.primevideo.com/detail/0U3TA8SOFL6VTAQ1E1QSC0SA6D/ref=atv_dp_season_select_s1", "name": "Amazon Prime Video"}, {"url": "https://www.youtube.com/playlist?list=PLwLSw1_eDZl1pvIv1fBd3oKkP3XEQpT_G", "name": "YouTube"}, {"url": "https://www.hulu.com/series/mob-psycho-100-fc9b8130-e1e3-420b-b28d-a72f0b235069", "name": "Hulu"}]	https://anilist.co/anime/21507	2026-10-07 00:29:48.599464+00	2026-10-07 00:29:48.621627+00	2026-10-07 00:29:48.621627+00
anilist-21355	anilist	21355	anime	Re:ZERO -Starting Life in Another World-	Re:ゼロから始める異世界生活	In the story, Subaru Natsuki is an ordinary high school student who is lost in an alternate world, where he is rescued by a beautiful, silver-haired girl. He stays near her to return the favor, but the destiny she is burdened with is more than Subaru can imagine. Enemies attack one by one, and both of them are killed. He then finds out he has the power to rewind death, back to the time he first came to this world. But only he remembers what has happened since. (Source: Anime News Network) Notes: - The first episode aired with a runtime of ~50 minutes as opposed to the standard 25 minute long episode. - In the Winter 2020 season, Re:ZERO was rebroadcast and re-edited to fit into an hour time-slot. This edit included the first OVA and added slight modifications to certain scenes throughout. It also added an additional scene at the end of the final episode.	["Action", "Adventure", "Drama", "Fantasy", "Psychological", "Romance", "Thriller"]	https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21355-wRVUrGxpvIQQ.jpg	https://s4.anilist.co/file/anilistcdn/media/anime/banner/21355-f9SjOfEJMk5P.jpg	WHITE FOX	25	8.1	2016	NR	tv	finished	JP	vFfXjuVA1Jk	https://anilist.co/anime/21355	[{"url": "https://www.netflix.com/title/80131659", "name": "Netflix"}, {"url": "https://www.youtube.com/playlist?list=PLwLSw1_eDZl0_movujO4K0xYOAG9soPjH", "name": "YouTube"}, {"url": "https://www.hulu.com/series/03f5afe1-1092-45ee-a421-91d0d8413bf0", "name": "Hulu"}, {"url": "https://www.youtube.com/@Rezero_official", "name": "YouTube"}]	https://anilist.co/anime/21355	2026-10-07 00:29:48.599516+00	2026-10-07 00:29:48.621627+00	2026-10-07 00:29:48.621627+00
anilist-20665	anilist	20665	anime	Your lie in April	四月は君の嘘	Piano prodigy Arima Kousei dominated the competition and all child musicians knew his name. But after his mother, who was also his instructor, passed away, he had a mental breakdown while performing at a recital. This resulted in him no longer being able to hear the sound of his piano playing. Two years later, Kousei hasn’t touched the piano and views the world without any flair or color. He was content at living out his life with his good friends Tsubaki and Watari until, one day, a girl changed everything. Miyazono Kaori is a pretty, free spirited violinist whose playing style reflects her personality. Kaori helps Kousei return to the music world and show that it should be free and mold breaking unlike the structured and rigid style Kousei was used to.	["Drama", "Music", "Romance", "Slice of Life"]	https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20665-TLgkL8T8IRFd.png	https://s4.anilist.co/file/anilistcdn/media/anime/banner/20665-j4kSsfhfkM24.jpg	A-1 Pictures	22	8.4	2014	NR	tv	finished	JP	3aL0gDZtFbE	https://anilist.co/anime/20665	[{"url": "https://www.bilibili.tv/en/media/35121", "name": "Bilibili TV"}, {"url": "https://www.netflix.com/title/80041089", "name": "Netflix"}]	https://anilist.co/anime/20665	2026-10-07 00:29:48.59956+00	2026-10-07 00:29:48.621627+00	2026-10-07 00:29:48.621627+00
anilist-104578	anilist	104578	anime	Attack on Titan Season 3 Part 2	進撃の巨人 Season３ Part.2	The battle to retake Wall Maria begins now! With Eren’s new hardening ability, the Scouts are confident they can seal the wall and take back Shiganshina District. If they succeed, Eren can finally unlock the secrets of the basement—and the world. But danger lies in wait as Reiner, Bertholdt, and the Beast Titan have plans of their own. Could this be humanity’s final battle for survival? (Source: Funimation)	["Action", "Drama", "Fantasy", "Mystery"]	https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx104578-k61nx3LPjvgd.jpg	https://s4.anilist.co/file/anilistcdn/media/anime/banner/104578-z7SadpYEuAsy.jpg	WIT STUDIO	10	8.9	2019	NR	tv	finished	JP	fJm2nD3cv_4	https://anilist.co/anime/104578	[{"url": "https://www.crunchyroll.com/attack-on-titan", "name": "Crunchyroll"}, {"url": "https://www.hulu.com/series/attack-on-titan-9c91ffa3-dc20-48bf-8bc5-692e37c76d88", "name": "Hulu"}, {"url": "https://www.adultswim.com/videos/attack-on-titan", "name": "Adult Swim"}, {"url": "https://www.netflix.com/title/70299043", "name": "Netflix"}, {"url": "https://www.crunchyroll.com/attack-on-titan-dubs", "name": "Crunchyroll"}]	https://anilist.co/anime/104578	2026-10-07 00:29:48.599589+00	2026-10-07 00:29:48.621627+00	2026-10-07 00:29:48.621627+00
\.


--
-- Data for Name: favorites; Type: TABLE DATA; Schema: public; Owner: anivideos
--

COPY public.favorites (user_id, content_id, created_at) FROM stdin;
\.


--
-- Data for Name: featured_banners; Type: TABLE DATA; Schema: public; Owner: anivideos
--

COPY public.featured_banners (id, content_id, eyebrow, display_order, is_active, created_at, updated_at) FROM stdin;
featured-anilist-5114	anilist-5114	Anime destacado	0	t	2026-10-07 00:29:48.657374+00	2026-10-07 00:29:48.657374+00
featured-anilist-104578	anilist-104578	Anime destacado	1	t	2026-10-07 00:29:48.657374+00	2026-10-07 00:29:48.657374+00
featured-anilist-11061	anilist-11061	Anime destacado	2	t	2026-10-07 00:29:48.657374+00	2026-10-07 00:29:48.657374+00
featured-anilist-20954	anilist-20954	Anime destacado	3	t	2026-10-07 00:29:48.657374+00	2026-10-07 00:29:48.657374+00
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: anivideos
--

COPY public.users (id, username, email, password_hash, avatar_url, display_name, bio, is_active, created_at, updated_at) FROM stdin;
\.


--
-- Name: banner_comments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: anivideos
--

SELECT pg_catalog.setval('public.banner_comments_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: anivideos
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- Name: alembic_version alembic_version_pkc; Type: CONSTRAINT; Schema: public; Owner: anivideos
--

ALTER TABLE ONLY public.alembic_version
    ADD CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num);


--
-- Name: auth_sessions auth_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: anivideos
--

ALTER TABLE ONLY public.auth_sessions
    ADD CONSTRAINT auth_sessions_pkey PRIMARY KEY (token_hash);


--
-- Name: banner_comments banner_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: anivideos
--

ALTER TABLE ONLY public.banner_comments
    ADD CONSTRAINT banner_comments_pkey PRIMARY KEY (id);


--
-- Name: content_items content_items_pkey; Type: CONSTRAINT; Schema: public; Owner: anivideos
--

ALTER TABLE ONLY public.content_items
    ADD CONSTRAINT content_items_pkey PRIMARY KEY (id);


--
-- Name: favorites favorites_pkey; Type: CONSTRAINT; Schema: public; Owner: anivideos
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT favorites_pkey PRIMARY KEY (user_id, content_id);


--
-- Name: featured_banners featured_banners_pkey; Type: CONSTRAINT; Schema: public; Owner: anivideos
--

ALTER TABLE ONLY public.featured_banners
    ADD CONSTRAINT featured_banners_pkey PRIMARY KEY (id);


--
-- Name: content_items uq_content_provider_id; Type: CONSTRAINT; Schema: public; Owner: anivideos
--

ALTER TABLE ONLY public.content_items
    ADD CONSTRAINT uq_content_provider_id UNIQUE (source, external_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: anivideos
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: anivideos
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: anivideos
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: ix_auth_sessions_expires; Type: INDEX; Schema: public; Owner: anivideos
--

CREATE INDEX ix_auth_sessions_expires ON public.auth_sessions USING btree (expires_at);


--
-- Name: ix_auth_sessions_user; Type: INDEX; Schema: public; Owner: anivideos
--

CREATE INDEX ix_auth_sessions_user ON public.auth_sessions USING btree (user_id);


--
-- Name: ix_banner_comments_banner_created; Type: INDEX; Schema: public; Owner: anivideos
--

CREATE INDEX ix_banner_comments_banner_created ON public.banner_comments USING btree (banner_id, created_at);


--
-- Name: ix_banner_comments_user; Type: INDEX; Schema: public; Owner: anivideos
--

CREATE INDEX ix_banner_comments_user ON public.banner_comments USING btree (user_id);


--
-- Name: ix_content_category_year_score; Type: INDEX; Schema: public; Owner: anivideos
--

CREATE INDEX ix_content_category_year_score ON public.content_items USING btree (category, release_year, score);


--
-- Name: ix_content_title; Type: INDEX; Schema: public; Owner: anivideos
--

CREATE INDEX ix_content_title ON public.content_items USING btree (title);


--
-- Name: ix_favorites_user_created; Type: INDEX; Schema: public; Owner: anivideos
--

CREATE INDEX ix_favorites_user_created ON public.favorites USING btree (user_id, created_at);


--
-- Name: ix_featured_active_order; Type: INDEX; Schema: public; Owner: anivideos
--

CREATE INDEX ix_featured_active_order ON public.featured_banners USING btree (is_active, display_order);


--
-- Name: ix_users_email_lower; Type: INDEX; Schema: public; Owner: anivideos
--

CREATE UNIQUE INDEX ix_users_email_lower ON public.users USING btree (lower((email)::text));


--
-- Name: ix_users_username_lower; Type: INDEX; Schema: public; Owner: anivideos
--

CREATE UNIQUE INDEX ix_users_username_lower ON public.users USING btree (lower((username)::text));


--
-- Name: auth_sessions auth_sessions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: anivideos
--

ALTER TABLE ONLY public.auth_sessions
    ADD CONSTRAINT auth_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: banner_comments banner_comments_banner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: anivideos
--

ALTER TABLE ONLY public.banner_comments
    ADD CONSTRAINT banner_comments_banner_id_fkey FOREIGN KEY (banner_id) REFERENCES public.featured_banners(id) ON DELETE CASCADE;


--
-- Name: banner_comments banner_comments_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: anivideos
--

ALTER TABLE ONLY public.banner_comments
    ADD CONSTRAINT banner_comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: favorites favorites_content_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: anivideos
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT favorites_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.content_items(id) ON DELETE CASCADE;


--
-- Name: favorites favorites_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: anivideos
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT favorites_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: featured_banners featured_banners_content_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: anivideos
--

ALTER TABLE ONLY public.featured_banners
    ADD CONSTRAINT featured_banners_content_id_fkey FOREIGN KEY (content_id) REFERENCES public.content_items(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict QRltt9azaDR3tVajsDfMhhYfNt1bO8a8Jiy1fqdo0zlxVzfLpmasUXtx4jf8Q38

